<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.eqgVZdC' shared service.

return $this->privates['.service_locator.eqgVZdC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'examinationRepository' => ['privates', 'App\\Repository\\ExaminationRepository', 'getExaminationRepositoryService.php', true],
], [
    'examinationRepository' => 'App\\Repository\\ExaminationRepository',
]);
