security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        app\Entity\User: bcrypt
        app\Entity\Employee: bcrypt
    providers:
        employees:
            entity:
                class: 'App\Entity\Employee'
                property: 'username'
        users:
            entity:
                class: 'App\Entity\User'
                property: 'username'
    firewalls:
        employee_login:
            provider: 'employees'
            anonymous: ~
            pattern: ^/employee/
            guard:
                authenticators:
                    - App\Security\EmployeeAuthenticator
            logout:
                path: employee_logout
        user_login:
            provider: 'users'
            anonymous: ~
            pattern: ^/
            guard:
                authenticators:
                    - App\Security\UserAuthenticator
            logout:
                path: user_logout
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
