<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.RzZh2sL' shared service.

return $this->privates['.service_locator.RzZh2sL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'employeeManager' => ['privates', 'App\\Managers\\EmployeeManager', 'getEmployeeManagerService.php', true],
    'examinationRepository' => ['privates', 'App\\Repository\\ExaminationRepository', 'getExaminationRepositoryService.php', true],
], [
    'employeeManager' => 'App\\Managers\\EmployeeManager',
    'examinationRepository' => 'App\\Repository\\ExaminationRepository',
]);
