<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUHyM5ZH\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUHyM5ZH/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUHyM5ZH.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUHyM5ZH\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUHyM5ZH\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UHyM5ZH',
    'container.build_id' => '317de4fb',
    'container.build_time' => 1575561444,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUHyM5ZH');
